### ISSUE TITLE
schedule expressions with a "/" are not parsed correctly

### ISSUE THREAD

**Issue by coulonxyz** [beemhq/aws-cron-parser#13]
It seems that the frequency is not calculated when adding a "/" in the expression.

```
import awsCronParser from 'aws-cron-parser';

describe('should generate next & prev occurence for various crons', () => {
  let occurence;

  const base = new Date(Date.UTC(2020, 5 - 1, 9, 22, 30, 57));

  const crons = [
    [
      '0-29 22 09 05 ? 2020',
      undefined,
      'Sat, 09 May 2020 22:29:00 GMT',
    ],
    [
      '0-29/1 22 09 05 ? 2020',
      undefined,
      'Sat, 05 Sep 2020 22:25:00 GMT',
    ],
    [
      '0-29/5 22 09 05 ? 2020',
      undefined,
      'Sat, 05 Sep 2020 22:25:00 GMT',
    ],
  ];

  test.each(crons)(
    'should figure out previous and next occurrence for %s',
    (cron, nextShouldBe, prevShouldBe) => {
      const parsed = awsCronParser.parse(cron);

      occurence = awsCronParser.next(parsed, base);
      expect(occurence?.toUTCString()).toBe(nextShouldBe);

      occurence = awsCronParser.prev(parsed, base);
      expect(occurence?.toUTCString()).toBe(prevShouldBe);
    },
  );
});
```
Unfortunately, the test 2 & 3 are failing.
Here are the results:
```
 FAIL  tests/events/domain/unit/cron.test.ts (6.754 s)
  should generate next & prev occurence for various crons
    ✓ should figure out previous and next occurrence for 0-29 22 09 05 ? 2020 (3 ms)
    ✕ should figure out previous and next occurrence for 0-29/1 22 09 05 ? 2020 (3 ms)
    ✕ should figure out previous and next occurrence for 0-29/5 22 09 05 ? 2020 (1 ms)

  ● should generate next & prev occurence for various crons › should figure out previous and next occurrence for 0-29/1 22 09 05 ? 2020

    expect(received).toBe(expected) // Object.is equality

    Expected: undefined
    Received: "Sat, 09 May 2020 22:31:00 GMT"

      30 | 
      31 |       occurence = awsCronParser.next(parsed, base);
    > 32 |       expect(occurence?.toUTCString()).toBe(nextShouldBe);
         |                                        ^
      33 | 
      34 |       occurence = awsCronParser.prev(parsed, base);
      35 |       expect(occurence?.toUTCString()).toBe(prevShouldBe);

      at tests/events/domain/unit/cron.test.ts:32:40

  ● should generate next & prev occurence for various crons › should figure out previous and next occurrence for 0-29/5 22 09 05 ? 2020

    expect(received).toBe(expected) // Object.is equality

    Expected: undefined
    Received: "Sat, 09 May 2020 22:35:00 GMT"

      30 | 
      31 |       occurence = awsCronParser.next(parsed, base);
    > 32 |       expect(occurence?.toUTCString()).toBe(nextShouldBe);
         |                                        ^
      33 | 
      34 |       occurence = awsCronParser.prev(parsed, base);
      35 |       expect(occurence?.toUTCString()).toBe(prevShouldBe);

      at tests/events/domain/unit/cron.test.ts:32:40

Test Suites: 1 failed, 1 total
Tests:       2 failed, 1 passed, 3 total
Snapshots:   0 total
Time:        6.8 s, estimated 7 s
Ran all test suites matching /cron.test.ts/i.
```

**Comment by silveoj** [comment]
I try to parse some expressions. Doesn't work. Maybe it's specific flavor which aws-cron-parser doesn't support by spec.

`* * * * * ? *`
`0 10 1/1 * ?`
`3 0/1 1/1 * *`
`0 0/1 * 1/1 * ? *`
`0,33 0 0 ? * * *`

To generate it I use
https://www.freeformatter.com/cron-expression-generator-quartz.html
https://claudiuconstantin.github.io/cron-editor/
https://haavardj.github.io/ngx-cron-editor/

1. `"Cannot read property 'getTime' of null"`
2. `AwsCronParser : this shouldn't happen, but iter > 10`
3. `Cannot read property 'endsWith' of undefined`

**Comment by vinhtnguyen** [comment]
@silveoj actually the cron expressions used by AWS is a little bit specific and different. That's why this package is only meant to address the AWS's specs. You can validate if the cron expression is valid with AWS EventBridge page like in this screenshot. Hope this helps.
![Screen Shot 2021-05-05 at 8 42 34 PM](https://user-images.githubusercontent.com/6675339/117226376-875a7a80-ade2-11eb-8e08-885c762aaa09.png)

**Comment by vinhtnguyen** [comment]
@coulonxyz thank you for reporting the non-working cron expressions. I will enhance this package to support them properly.
